apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: demo
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: database
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: secret/database
        property: password
    - secretKey: user
      remoteRef:
        key: secret/database
        property: user
